### ISSUE TITLE
Any interest in implementing CircularMean?

### ISSUE THREAD

**Issue by rikonor** [gonum/stat#141]
I've recently had to calculate a [circular mean](https://en.wikipedia.org/wiki/Mean_of_circular_quantities) for a series of angles and noticed it's not implemented in gonum/stat.
If there's any interest I'd be happy to submit a PR for it.

**Comment by jonlawlor** [comment]
I'll defer to others about where exactly it might belong, but it does appear in scipy under scipy.stats.morestats, R has it under a circular package, there's a pretty mature matlab "toolbox" on matlabcentral.  That doesn't mean we have to, but it indicates to me that it does have a certain level of utility.

It is a bit unusual (I have never used directional statistics myself) but not so specific that we would exclude it I think.  Maybe in a new sub-repository stat/circular or stat/directional ?  Thoughts anyone...

**Comment by btracey** [comment]
We have a bunch of weird distances in gonum/stat. I'd just put it there unless there are a whole bunch of variations on a theme.

**Comment by jonlawlor** [comment]
I did a brief survey of the methods implemented elsewhere and a few textbook table of contents and it looks like it can go from standard summary statistics (mean, var, std) on one end all the way up to recreating the statistics package using directional statistics on the other.

Maybe just put the standard summary statistics in stat and if anything goes past that put it into a sub-repository?
