### ISSUE TITLE
stat/distuv: introduce Func()

### ISSUE THREAD

**Issue by sbinet** [gonum/stat#143]
hi there,

what about having this:

```go
func (n *Normal) Func() func(x float64) float64 {
    mu := n.Mu
    sigma := n.Sigma
    sigma2 := 2*sigma*sigma
    root2pi := math.Sqrt(2*math.Pi)
    return func(x float64) float64 {
        return 1 / (sigma * root2pi) * math.Exp(-((x-mu)*(x-mu))/sigma2)    
    }
```

(and similarly for the other distributions)

this would allow to easily compare (and plot) distributions and their underlying function.

**Comment by sbinet** [comment]
ah! `.Prob()` of course does that.

**Comment by btracey** [comment]
That would have been a bold design choice
