### ISSUE TITLE
stat/distuv: Adding F-distribution

### ISSUE THREAD

**Issue by dongweigogo** [gonum/stat#172]
Hello! I'm doing some statistical work with this package recently, and find it is very useful and practical. 

However the F-distribution (Fisher–Snedecor distribution) is still missing from the distuv module, that is required for the Levene test to assert equality of variances for Student's T test of independent samples. So, I think it is necessary to add the F-distribution to the type list. This will definitely make the package more powerful.

**Comment by btracey** [comment]
This was done.
