### ISSUE TITLE
Population variance vs sample variance

### ISSUE THREAD

**Issue by dongweigogo** [gonum/stat#180]
From the souce code, the sum of squared deviations is routinely divided by n-1, but not n. It seems that this package takes the sample variance and sample standard deviation as the default ones and many methods based on them, while packages of other languages (numpy, scipy of python) make the  population variance and population std as defaults. 
That is kind of misleading.

**Comment by btracey** [comment]
Why is it misleading? Other languages (matlab, R) compute the sample variance. The documentation clearly states it's the sample variance because of this confusion.

**Comment by dongweigogo** [comment]
@btracey 
Probably because I'm a heavy numpy and scipy user, and have been used to their conventions. 
Anyway, I'll read the docs again more carefully for those what I missed.

**Comment by btracey** [comment]
Unfortunately, impossible to match all implementations in this case
