### ISSUE TITLE
Median function in `stats`

### ISSUE THREAD

**Issue by rikonor** [gonum/stat#187]
Hi,

I was wondering - is there a desire to have a `Median([]float64) float64` function in `stats`?
I find myself in need of it and instead of implementing it (which, admittedly, is simple enough) in my code was thinking it'd be nicer to be able to use a standard `stats` implementation.

I'm happy to open a PR but thought I'd ask before as there may be a reason there isn't one already.

Or

**Comment by kortschak** [comment]
Does https://godoc.org/gonum.org/v1/gonum/stat#Quantile not work for you?
________________________________

**Comment by rikonor** [comment]
@kortschak Yes, I believe it will. I wasn't aware of that function - thanks for pointing it out.

On another note - it would seem to me that the naive way to find a median seems more performant then `Quantile`.

Closing the issue.

**Comment by kortschak** [comment]
If it becomes an issue for your user case, please reopen this.
