### ISSUE TITLE
sample: Sampler interface?

### ISSUE THREAD

**Issue by btracey** [gonum/stat#68]
The advanced sampling routines are implemented as functions at the moment. I wonder if they should be types instead. This would allow abstracting over the kind of sampling. The most common would be

```
// A Sampler can generate a set of values generated using an underlying sampling algorithm. The number of samples generated 
type Sampler interface{
       Sample([]float64)
}
```

This would allow other algorithms to be written on top of this interface.

**Comment by kortschak** [comment]
SGTM

Maybe define types that use the currently existing functions and retain them?

**Comment by btracey** [comment]
What would you suggest for a naming scheme?

**Comment by kortschak** [comment]
`Funcer` for each func?
