### ISSUE TITLE
installation of gonum/stat failed

### ISSUE THREAD

**Issue by ebusato** [gonum/stat#71]
Hi,

Apologize in advance if my question is naive, I'm very new to golang and gonum packages. 

I tried installing gonum/stat with 

     go get github.com/gonum/stat

but I get the following error:

    matrix/mat64/vector.go:134: undefined: asm.DscalIncTo
    matrix/mat64/vector.go:142: undefined: asm.DscalInc

I'm running go1.5.2 on ubuntu 14.04.3 LTS. 

Thanks for any help,
Emmanuel

**Comment by sbinet** [comment]
salut Manu,

I just tried in a fresh `$GOPATH` workspace:

```sh
$> go get -v github.com/gonum/stat
github.com/gonum/stat (download)
github.com/gonum/floats (download)
github.com/gonum/internal (download)
github.com/gonum/matrix (download)
github.com/gonum/lapack (download)
github.com/gonum/blas (download)
github.com/gonum/blas
github.com/gonum/internal/asm
github.com/gonum/blas/native/internal/math32
github.com/gonum/floats
github.com/gonum/lapack
github.com/gonum/blas/native
github.com/gonum/matrix
github.com/gonum/blas/blas64
github.com/gonum/lapack/native
github.com/gonum/lapack/lapack64
github.com/gonum/matrix/mat64
github.com/gonum/stat
```

it worked.

I have seen a few pull requests go by in the `matrix` and `asm` areas.
You probably have a stale package.

Could you try updating `stat` and its dependencies? like so:

```sh
$> go get -u -v github.com/gonum/stat
```

hth,
-s

**Comment by ebusato** [comment]
This works, great !

Thanks seb !
